#####Start Jenkins container using docker-compose
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: myjenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /mnt/g/docker-volumes/jenkins_home:/var/jenkins_home
      - /mnt/g/docker-volumes/jenkins_lib:/var/lib
    restart: always
